import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Painel Admin",
  description: "Generated by Pedro Ramos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="pt-BR" suppressHydrationWarning>
      <head />
      <body className="flex min-h-screen">
      <Sidebar /> 
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
      <main className="flex-1 bg-muted/40 p-6" >{children}</main>
      </ThemeProvider>
      </body>
    </html>
  </>
  );
}
